services:
  - type: web
    name: road-rescue
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'app:create_app()'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_MAPS_API_KEY
        sync: false
